### PR TITLE
Upstream plus prs

### PR DESCRIPTION
**Pull request by jyellick**
This diff likely won't display correctly in Github.  So, you may want to try looking at it locally.

The commit history isn't as clean as I'd like it, but, the resulting diff from upstream remains pretty small.

Some things I don't like:

1. The op-bindings I hacked by hand, adding in the `registry.go` file and deleting some of the BOBA bindings that conflicted with the GovernanceToken.  But, my impression is that was done before.
2. I ended up merging upstream multiple times before pushing this.  It seems some of what I pulled in wasn't actually working, so needed to grab newer stuff.
3. This includes the PRs that I've submitted upstream, but have not been merged.  So, depending on feedback, they may generated conflicts we'll have to resolve in the future.

But, all things considered, the devnet tests are passing, the e2e is passing, I think this is worth merging.

### CODE REVIEW

**Review by boyuan-chen — APPROVED** [review]
Overall, it looks good to me. Some old stuffs are deleted and some migration code are deleted.

**Comment by mmontour1306** [comment]
I'm getting a failure on "make devnet-up":

```
PYTHONPATH=./bedrock-devnet python3 ./bedrock-devnet/main.py --monorepo-dir=.
Traceback (most recent call last):
  File "./bedrock-devnet/main.py", line 1, in <module>
    import devnet
  File "/home/enya/_clean/v3-anchorage/bedrock-devnet/devnet/__init__.py", line 20, in <module>
    parser.add_argument('--deploy', help='Whether the contracts should be predeployed or deployed', type=bool, action=argparse.BooleanOptionalAction)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
make: *** [Makefile:85: devnet-up] Error 1
```

**Comment by boyuan-chen** [comment]
I have a different error of running `make devnet-up`
```
~/Downloads/v3-anchorage-upstream-plus-prs ❯ make devnet-up                                                                                           1m 51s 12:47:15 PM
PYTHONPATH=./bedrock-devnet python3 ./bedrock-devnet/main.py --monorepo-dir=.
WARN[0000] The "L2OO_ADDRESS" variable is not set. Defaulting to a blank string. 
#1 [l1 internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.1s

#2 [l1 internal] load build definition from Dockerfile.l1
#2 transferring dockerfile: 280B done
#2 DONE 0.1s

#3 [l2 internal] load .dockerignore
#3 transferring context: 256B done
#3 DONE 0.0s

#4 [l2 internal] load build definition from Dockerfile.l2-erigon
#4 transferring dockerfile: 1.63kB done
#4 DONE 0.1s

#5 [l2] resolve image config for docker.io/docker/dockerfile:1.2
#5 DONE 0.6s

#6 [l2] docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b95912df1cf7d313c3e2230a333fdbcc
#6 CACHED

#7 [l1 internal] load metadata for docker.io/ethereum/client-go:v1.12.0
#7 DONE 0.7s

#8 [l1 1/3] FROM docker.io/ethereum/client-go:v1.12.0@sha256:c601019e4426e1320d59631c0d55005c64da641455da97a0b79f89b617707685
#8 DONE 0.0s

#9 [l1 internal] load build context
#9 transferring context: 121B done
#9 DONE 0.0s

#10 [l1 2/3] RUN apk add --no-cache jq
#10 CACHED

#11 [l1 3/3] COPY entrypoint-l1.sh /entrypoint.sh
#11 CACHED

#12 [l1] exporting to image
#12 exporting layers done
#12 writing image sha256:25baf84c347f4771d9593c12e33dfd967a60d3aa3a73f3437d9f8a3e93f31af4 done
#12 naming to docker.io/library/ops-bedrock-l1 done
#12 DONE 0.0s

#13 [l2 internal] load build definition from Dockerfile.l2-erigon
#13 DONE 0.0s

#14 [l2 internal] load .dockerignore
#14 DONE 0.0s

#15 [op-node internal] load build definition from Dockerfile
#15 transferring dockerfile: 777B done
#15 DONE 0.0s

#16 [op-node internal] load .dockerignore
#16 transferring context: 256B done
#16 DONE 0.0s

#17 [op-node internal] load metadata for docker.io/library/golang:1.19.9-alpine3.16
#17 ...

#18 [l2 internal] load metadata for docker.io/library/alpine:3.17
#18 DONE 0.5s

#19 [op-node internal] load metadata for docker.io/library/alpine:3.16
#19 DONE 0.5s

#20 [l2 internal] load metadata for docker.io/library/golang:1.20-alpine3.17
#20 DONE 0.7s

#21 [l2 builder 1/8] FROM docker.io/library/golang:1.20-alpine3.17@sha256:3e37b07200894d0638ec9d8276c5a8329e225da3b796ac506df6e11b381922e7
#21 DONE 0.0s

#22 [l2 stage-1 1/9] FROM docker.io/library/alpine:3.17@sha256:e95676db9e4a4f16f6cc01a8915368f82b018cc07aba951c1bd1db586c081388
#22 DONE 0.0s

#23 [l2 stage-1 2/9] RUN apk add --no-cache ca-certificates libstdc++ tzdata
#23 CACHED

#24 [l2 stage-1 3/9] RUN apk add --no-cache curl jq bind-tools
#24 CACHED

#25 [l2 stage-1 4/9] RUN adduser -D -u 1000 -g 1000 erigon
#25 CACHED

#26 [l2 stage-1 5/9] RUN mkdir -p ~/.local/share/erigon
#26 CACHED

#27 [l2 internal] load build context
#27 transferring context: 1.08kB done
#27 DONE 0.0s

#17 [op-node internal] load metadata for docker.io/library/golang:1.19.9-alpine3.16
#17 DONE 0.7s

#28 [l2 builder 2/8] RUN apk --no-cache add build-base linux-headers git bash ca-certificates libstdc++
#28 CACHED

#29 [l2 builder 3/8] WORKDIR /app
#29 CACHED

#30 [l2 builder 4/8] ADD ../op-erigon/go.mod go.mod
#30 CACHED

#31 [l2 builder 5/8] ADD ../op-erigon/go.sum go.sum
#31 CACHED

#32 [op-node stage-1 1/2] FROM docker.io/library/alpine:3.16@sha256:cbe5d5973103a2d03408d1689a6efde4ea4920bde9f4b51fe7872e60ce2d8e56
#32 CACHED

#33 [op-node builder  1/12] FROM docker.io/library/golang:1.19.9-alpine3.16@sha256:7d7cc4682f31c69ac36c34cdbd2a5d1963c7c007ed423b7b58b73613ae085e39
#33 resolve docker.io/library/golang:1.19.9-alpine3.16@sha256:7d7cc4682f31c69ac36c34cdbd2a5d1963c7c007ed423b7b58b73613ae085e39 done
#33 sha256:7d7cc4682f31c69ac36c34cdbd2a5d1963c7c007ed423b7b58b73613ae085e39 1.65kB / 1.65kB done
#33 sha256:9c10ae7a280cab3092646406901f65a60722cf8f6db3a338f4ef471fd884fd84 1.16kB / 1.16kB done
#33 sha256:0ac4d91735c5b2ccf1055b8c36bd4e444842f015f550de7ec8c198423d255a03 5.12kB / 5.12kB done
#33 CANCELED

#34 [op-node internal] load build context
#34 transferring context: 64.61kB 0.0s done
#34 DONE 0.1s

#35 [op-node builder  8/12] COPY ./go.sum /app/go.sum
#35 CACHED

#36 [op-node builder  4/12] COPY ./op-chain-ops /app/op-chain-ops
#36 CACHED

#37 [op-node builder  2/12] RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash
#37 CACHED

#38 [op-node builder  5/12] COPY ./op-service /app/op-service
#38 CACHED

#39 [op-node builder  7/12] COPY ./go.mod /app/go.mod
#39 CACHED

#40 [op-node builder  6/12] COPY ./op-bindings /app/op-bindings
#40 CACHED

#41 [op-node builder  3/12] COPY ./op-node /app/op-node
#41 CACHED

#42 [op-node builder  9/12] COPY ./.git /app/.git
#42 ERROR: failed to calculate checksum of ref 912d11dc-735b-427f-83ce-50284cce731d::hx6ymlneq6hnx3t2c69l3cpa3: "/.git": not found

#43 [l2 builder 6/8] RUN go mod download
#43 CANCELED
```
The building process gets stuck.

**Comment by jyellick** [comment]
Hmm, just re-tested this locally and it works for me.

@mmontour1306 This line was added upstream when they moved from bash to python for the devnet script.  My guess is an incompatible version of python or the imported dependency?

@Boyuan-Chen This error is very odd to me, but seems like it's originating from Docker, maybe something transient, or filespace or something?

[edit: switched the individual questions]

Did you each try running `make devnet-clean`  before the `make devnet-up`?

Can you confirm that `make devnet-up` is working for you on the upstream `develop` branch?

**Comment by mmontour1306** [comment]
I am getting the same error on the upstream develop branch. "make devnet-clean" doesn't help.

**Comment by jyellick** [comment]
Oops, looks like I got your problems backwards (but edited and fixed above)

@Boyuan-Chen  Looks like it may be related to your docker env?  Seems like there have been a lot of similar problems, but note the one at the end of this thread: https://github.com/docker/build-push-action/issues/558 perhaps you updated docker recently or some such?  Difficult for me to debug, given that it runs upstream, locally, and in CI.

@mmontour1306 As yours looks like a python issue related to argparse, looks like that was added in 3.9 according to https://docs.python.org/3/library/argparse.html so perhaps you need to update?

**Comment by boyuan-chen** [comment]
> Oops, looks like I got your problems backwards
> 
> @Boyuan-Chen Looks like it may be related to your docker env? Seems like there have been a lot of similar problems, but note the one at the end of this thread: [docker/build-push-action#558](https://github.com/docker/build-push-action/issues/558) perhaps you updated docker recently or some such? Difficult for me to debug, given that it runs upstream, locally, and in CI.
> 
> @mmontour1306 As yours looks like a python issue related to argparse, looks like that was added in 3.9 according to https://docs.python.org/3/library/argparse.html so perhaps you need to update?

I found my problem. I should change my branch to this one and run `make devnet-up`. I downloaded this branch so that the git folder is not in it and `docker build` failed.

**Review by mmontour1306 — APPROVED** [review]
Approving despite the "make devnet-up" issue as that is the same upstream and is likely an undocumented Python version dependency (or at least I didn't see anything calling out the need for v3.9+).

**Pull request merged**
