### PR TITLE
Add script to verify l2 state

### PR DESCRIPTION
**Pull request by boyuan-chen**
`check-l2` can perform the state verification of l2 to make sure that all slots are setup correctly

Run `go run ./cmd/check-l2 --l2-rpc-url=https://l2.anchorage.boba.network` to verify the devnet

### CODE REVIEW

**Comment by mmontour1306** [comment]
What is the expected output? When I run "go run ./cmd/check-l2 --l2-rpc-url=https://l2.anchorage.boba.network" there are several warnings about proxy bytecode.

```
WARN[09-05|14:04:48.474] contract does not have the standard proxy bytecode name=SequencerFeeVault
WARN[09-05|14:04:48.834] contract does not have the standard proxy bytecode name=BaseFeeVault
WARN[09-05|14:04:49.121] contract does not have the standard proxy bytecode name=L2CrossDomainMessenger
WARN[09-05|14:04:50.126] contract does not have the standard proxy bytecode name=L2StandardBridge
WARN[09-05|14:04:50.599] contract does not have the standard proxy bytecode name=OptimismMintableERC20Factory
WARN[09-05|14:04:50.812] contract does not have the standard proxy bytecode name=L1BlockNumber
WARN[09-05|14:04:50.943] contract does not have the standard proxy bytecode name=L2ERC721Bridge
WARN[09-05|14:04:51.362] contract does not have the standard proxy bytecode name=ProxyAdmin
WARN[09-05|14:04:51.575] contract does not have the standard proxy bytecode name=L2ToL1MessagePasser
WARN[09-05|14:04:51.788] contract does not have the standard proxy bytecode name=DeployerWhitelist
WARN[09-05|14:04:51.991] contract does not have the standard proxy bytecode name=L1Block
WARN[09-05|14:04:52.131] contract does not have the standard proxy bytecode name=LegacyMessagePasser
WARN[09-05|14:04:52.269] contract does not have the standard proxy bytecode name=L1FeeVault
WARN[09-05|14:04:52.760] contract does not have the standard proxy bytecode name=GasPriceOracle
WARN[09-05|14:04:52.966] contract does not have the standard proxy bytecode name=OptimismMintableERC721Factory
WARN[09-05|14:04:53.226] contract does not have the standard proxy bytecode name=BobaTuringCredit
WARN[09-05|14:04:53.759] contract does not have the standard proxy bytecode name=BobaGasPriceOracle

```

**Comment by boyuan-chen** [comment]
> What is the expected output? When I run "go run ./cmd/check-l2 --l2-rpc-url=https://l2.anchorage.boba.network" there are several warnings about proxy bytecode.
> 
> ```
> WARN[09-05|14:04:48.474] contract does not have the standard proxy bytecode name=SequencerFeeVault
> WARN[09-05|14:04:48.834] contract does not have the standard proxy bytecode name=BaseFeeVault
> WARN[09-05|14:04:49.121] contract does not have the standard proxy bytecode name=L2CrossDomainMessenger
> WARN[09-05|14:04:50.126] contract does not have the standard proxy bytecode name=L2StandardBridge
> WARN[09-05|14:04:50.599] contract does not have the standard proxy bytecode name=OptimismMintableERC20Factory
> WARN[09-05|14:04:50.812] contract does not have the standard proxy bytecode name=L1BlockNumber
> WARN[09-05|14:04:50.943] contract does not have the standard proxy bytecode name=L2ERC721Bridge
> WARN[09-05|14:04:51.362] contract does not have the standard proxy bytecode name=ProxyAdmin
> WARN[09-05|14:04:51.575] contract does not have the standard proxy bytecode name=L2ToL1MessagePasser
> WARN[09-05|14:04:51.788] contract does not have the standard proxy bytecode name=DeployerWhitelist
> WARN[09-05|14:04:51.991] contract does not have the standard proxy bytecode name=L1Block
> WARN[09-05|14:04:52.131] contract does not have the standard proxy bytecode name=LegacyMessagePasser
> WARN[09-05|14:04:52.269] contract does not have the standard proxy bytecode name=L1FeeVault
> WARN[09-05|14:04:52.760] contract does not have the standard proxy bytecode name=GasPriceOracle
> WARN[09-05|14:04:52.966] contract does not have the standard proxy bytecode name=OptimismMintableERC721Factory
> WARN[09-05|14:04:53.226] contract does not have the standard proxy bytecode name=BobaTuringCredit
> WARN[09-05|14:04:53.759] contract does not have the standard proxy bytecode name=BobaGasPriceOracle
> ```

Optimism updated their proxy contract, so the version we deployed on devnet is different from what we have in `contract-bedrock`. It verifies all slots in the pre-deployed contracts.

**Comment by boyuan-chen** [comment]
This RP can improve this PR: https://github.com/bobanetwork/v3-anchorage/pull/40

Once we merge this to the develop branch, we can remove these comments:
https://github.com/bobanetwork/v3-anchorage/blob/7cd2a46ccfc0abeea0ebbe555bd31952ef0d4afc/bedrock-devnet/hardhat/__init__.py#L261-L265

**Review by jyellick — APPROVED** [review]
LGTM, I was able to run successfully (aside from the Warnings about proxy contract already discussed)

**Review by mmontour1306 — APPROVED** [review]

**Pull request merged**
