### PR TITLE
Merge upstream plus fixes 20230825

### PR DESCRIPTION
**Pull request by jyellick**
This is another large merge commit, complete with lots of conflict resolution.

The goal had been to merge upstream weekly, and, you'll actually find roughly weekly merge commits in this PR.

Unfortunately, test failures, and then other priorities failed to turn these initial merges into PRs.

This PR turns almost everything green, with the exception of some of the boba-bindings and boba-chain-ops.  This may need to be addressed before merging, but I wanted to get this out there so that others could look at it and see the problems I'm describing.

It may be worth merging as is and cleaning up.  Or, we may want to address some of these problems.

### CODE REVIEW

**Comment by boyuan-chen** [comment]
@jyellick `make devnet-up` doesn't work on my end.

**Comment by mmontour1306** [comment]
I get an error on "make devnet-up":
"failed to write to "/home/enya/v3-boba/optimism/packages/contracts-bedrock/deployments/devnetL1/.chainId": No such file or directory (os error 2)"

Creating the directory manually before running the command allows it to proceed.

**Comment by mmontour1306** [comment]
Also, "packages/contracts-bedrock/deploy-config/devnetL1.json" is checked into git but it's modified by running the devnet-up script (setting a new l1GenesisBlockTimestamp). Maybe we can have a read-only template checked into source control, and a .gitignore rule for the auto-generated version?

**Review by mmontour1306 — APPROVED** [review]
I made a couple of small comments above, but overall if you are happy with it then I would say to merge it and clean up any remaining issues later.

**Review by boyuan-chen — APPROVED** [review]

**Review by InoMurko — APPROVED** [review]

**Comment by jyellick** [comment]
Merging as there seems to be a consensus to do so.

@Boyuan-Chen How does `make devnet-up` fail on your end?  This works fine on my system.  I did find that I needed to do a: `make nuke`, then `make`, then `make devnet-up` in some cases.

@mmontour1306 I too have noticed the devnetL1 json file getting a new timestamp, this may be simply an upstream quirk, but I'll investigate.

**Pull request merged**
